# Server Configuration (8083 pour éviter les conflits)
server:
  port: 8083

# Application Name
spring:
  application:
    name: service-pronunciation

  datasource:
    url: jdbc:mysql://localhost:3306/skillforge_pronunciation?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

  # Audio storage configuration
  audio:
    storage:
      path: ./uploads/pronunciation

# Eureka Client Configuration
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    port: 8083


# Swagger / OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Logging
logging:
  level:
    org.springframework.web: DEBUG
    com.gestions.ramzi.servicepronunciation: DEBUG

