# MySQL Database Configuration
db=mysql
db-url=jdbc:mysql://localhost:3307/keycloak_db
db-username=root
db-password=

# Hostname configuration
hostname-strict=false
hostname-strict-https=false

# HTTP configuration
http-enabled=true
http-port=9090
