#
# Profil DEV (démarrage facile sans toucher la DB "elearning")
# Utilise une base dédiée + change le port pour éviter 8082 occupé.
#

server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/quiz_badge_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Pas d'Eureka en dev simple
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Formation-service direct (si tu le démarres)
spring.cloud.openfeign.client.config.formation-service.url=http://localhost:8081

